name: Build Template
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # clone the repo
      - name: Check out repository code
        uses: actions/checkout@v2
      # create the archive
      - name: Create the tgz archive
        run: tar -cvzf com.dorba.template.urp.base-10.5.1.tgz ./package
      # save as an artifact
      - name: Save the template
        uses: actions/upload-artifact@v2
        with:
          name: com.dorba.template.urp.base-10.5.1
          path: ./com.dorba.template.urp.base-10.5.1.tgz
