name: Build Template
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODO - output some useful information"
      # clone the repo
      - name: Check out repository code
        uses: actions/checkout@v2
      # create the archive
      - name: Create the tgz archive
        run: tar -cvzf package.tgz ./package
      # save as an artifact
      - name: Save the template
        uses: actions/upload-artifact@v2
        with:
          name: com.dorba.template.urp-base-10.5.1.tgz
          path: ./package.tgz
